### ISSUE TITLE
Image Count 问题

### ISSUE THREAD

**Issue by Monkey1GIt** [caj2pdf/caj2pdf#76]
除非特殊情况，请完整填写所有问题。不按模板发的 issue 将直接被关闭。
如果你遇到的问题不是 bug，比如你不清楚要如何配置，请使用[Discussion](https://github.com/caj2pdf/discussion/issues)进行讨论。

1) 你正在使用哪个版本的 CAJ2PDF？

最新版本

2) 你的使用场景是什么？比如convert还是其他。

convert

3) 你看到的不正常的现象是什么？（请描述具体现象，比如PDF打不开等）

转换后个别页图片显示不正确

4) 你期待看到的正确表现是怎样的？
图片应该正常显示

5) 请附上你的配置（Python版本、Python包版本以及mutools版本）。
Python 3.8.7
PyPDF2 1.26.0
mutool 1.18.0

6)  请附上出错时软件输出的错误信息。

错误信息:

出现报错如下
```bash
Page 23, Image Count 2 != 4
Page 33, Image Count 2 != 4
Page 69, Image Count 3 != 9
Page 70, Image Count 3 != 9
Page 72, Image Count 2 != 4
Page 73, Image Count 3 != 9
Page 78, Image Count 4 != 16
Page 87, Image Count 3 != 9
Page 91, Image Count 2 != 4
Page 92, Image Count 2 != 4
Page 95, Image Count 2 != 4
Page 128, Image Count 2 != 4
Page 129, Image Count 2 != 4
Page 130, Image Count 2 != 4
Page 135, Image Count 3 != 9
Page 136, Image Count 3 != 9
Page 137, Image Count 2 != 4
Page 138, Image Count 3 != 9
Page 141, Image Count 2 != 4
Page 142, Image Count 3 != 9
Page 143, Image Count 3 != 9
Page 144, Image Count 5 != 25
Page 145, Image Count 4 != 16
Page 146, Image Count 3 != 9
Page 147, Image Count 2 != 4
Page 150, Image Count 6 != 36
```
转换后结果:
![](https://s2.loli.net/2021/12/13/ep8gy1UvsFdwbHV.png)

请预览一下你填的内容再提交。

论文:
`基于星载合成孔径雷达干涉测量技术的数字高程模型生成研究_任坤.caj`
`基于压缩感知的合成孔径雷达超分辨成像复数据处理方法研究_曹轩.caj`
传输链接：https://cowtransfer.com/s/f9e8f6df7ef74b 
或
https://wss1.cn/f/73wpn29d95s

**Comment by HinTak** [comment]
The message / issue is the same as as few recent ones such as #73 and #69 . Before that, images are either full page, or wholy within a positioned window. But it seems that there are newer HN files, or maybe not newer, just we haven't seen before, which have images with clips/crops and positions.

The messages mean we don't understand it. Likely is that the images are not clipped - i.e. in those pages indicated, you have images which are smaller and contains more extra than the author intended . The intended image would be a small portion of what is showed, enlarged. we don't know the details yet.

You are free to try to understand the crop/clip by comparing with with the official conversion does.

**Comment by qinlili23333** [comment]
按照#72 中的描述这应该是特定版本HN所存在的一个bug导致的，图片数量被平方了 
或许可以在检测到数量不等时检查是否被平方，如果被平方则修正数据

**Comment by DarkOfTheMoon** [comment]
@HinTak 如果没有什么问题，请有时间时考虑一下将#72中提到的补丁合并进来吧

**Comment by HinTak** [comment]
@DarkOfTheMoon thanks for the work! I had a quick look, the change is larger than I would like, I think. For example, if squared is what the bug is, a much smaller change is needed (just suppressing the message - the code already trust the smaller value over the other). Anyway, I 'll try to find some time to look at the code in more detail, and the sample file too. Thanks a lot again.

**Comment by HinTak** [comment]
The sample file in https://github.com/caj2pdf/caj2pdf/pull/72 , 
https://github.com/caj2pdf/caj2pdf/files/7573979/_._.zip have most of the same problems - duplicate redundant images, and parsing for the image co-ordinates being wrong, and need revisiting.

For now, 基于星载合成孔径雷达干涉测量技术的数字高程模型生成研究_任坤.caj seems to work perfectly with the latest code. So the parsing for image co-ordindates and counts need to revisit 基于压缩感知的合成孔径雷达超分辨成像复数据处理方法研究_曹轩.caj and https://github.com/caj2pdf/caj2pdf/files/7573979/_._.zip

**Comment by HinTak** [comment]
The problem with this and #72 is that the page text positioning contains extra garbage, and the N images are embedded N times, so both of the sizes can be wrong.

We cannot do much about the text and figure positioning garbage . Improving parsing does not help - it is just extra at the end - maybe it involves text back tracking or some stop marker we don't understand yet - but they are extra garbage and looks like bits of other or same document embedded.

But for the latter, we can do a quick check to see the embedded image data have sizes [A B A B] or [A B C A B C A B C] and looks like 2 images twice or 3 images 3 times instead of 4 or 9 separate different 
images, so we can throw away image data that have the same data size, and get a correct count.  This is an extra routine to do that https://github.com/caj2pdf/caj2pdf/commit/1be03cf4f78fa697b09976d5fc6a492ecb48bc10 . With it, both this and #72 seems to convert perfectly now.
