### ISSUE TITLE
一些分析建议

### ISSUE THREAD

**Issue by znsoftm** [caj2pdf/caj2pdf#79]
看到库主做了很多有意义的工作，有一些建议：

1.  可以用ida pro进行静态分析或者ollydbg进行动态分析（windows下）
2.  可以加我微信聊聊： znsoft

**Comment by HinTak** [comment]
我認為純文本型NH文件不一定需要用ida pro那類工具。原則上，純文本，應是"字+位置"： 只要比較正式轉化和原本，分析什麼是＂位置＂，就行。

**Comment by HinTak** [comment]
@lelandyang have you got any documentation / reference tab BDPDL ? I am actually quite familiar with ESC/P actually . Having reverse-engineered one of Epson's non-ESC/P printer drivers - actually both HP and Epson do it: they produce printers which are driven by languages which use bits of PCL / PCL XL / ESC/P but also differ quite significantly - so familiarity with the core printer language helps to some extent when trying to re-implement those variant drivers for a different platform.

**Comment by lelandyang** [comment]
> @lelandyang have you got any documentation / reference about BDPDL ? I am actually quite familiar with ESC/P actually . Having reverse-engineered one of Epson's non-ESC/P printer drivers - actually both HP and Epson do it: they produce printers which are driven by languages which use bits of PCL / PCL XL / ESC/P but also differ quite significantly - so familiarity with the core printer language helps to some extent when trying to re-implement those variant drivers for a different platform.

Unfortunately, it is **NOT** an open standard, however, I reversed cajviewer and made some progress.

It is an internal standard for founder bookmaker (方正书版, or Fangzheng ShuBan, in pinyin), most Chinese publisher uses the software for publishing. Similar to LaTeX which produces dvi or PDF documents, bookmaker producers what is officially called "大样" files. The first releases of version 6.x complies with the original BDPDL by Kunqiu CHEN, the produced files has extensions **.S2**, but later versions made extensions and more instruction were added, and font encodings were changed (as you will find in ParseWits21, there are calls to functions such as `MapS72Char` , `WITS_21_S72::MapS72Symbol`, etc.). 

That is why function `WITS_21_S72::ParsePage` includes two branches, i.e. `WITS_21_S72::ParseWits21(this)`, meaning Parse higher versions of "大样" files, the other branch `WITS_21_S72::ParseSBS2(this)` means to parse ShuBanS2. 

All the BDPDL related parsing calls are located in two functions: `ParseWits21(this)` and `WITS_21_S72::ParseSBS2(this)`, in which corresponding command objects was created. The BDPDL is a varied length instruction set, almost every instruction begins with 0x80, every instruction is aligned to 4bytes (DWORD) because early implementation was in ASM and DWORD is easier to manipulate. For example instruction 0x8001 is composed of 4 bytes , the instruction denotes the vertical offset of a text, namely Y axis, two bytes following 0x8001 is a little-endian short int, denoting the Y value. Similarly, 0x8002 denotes font size and font type, which is also comprised of four bytes. The font mapping is done in function `ZhiHaotoSize` by using an array for mapping.

I will further investigate into it when I have the time.

**Comment by lelandyang** [comment]
> 

Extracting text is nothing difficult. 
"That sounds a lot like the stuff I was doing " I am afraid it is far from what you were doing, it's a complete set of instructions that allows complex layout. 
I have implemented in my own repo with a ground-up rewrite, and yet not fully finished due to my current tight schedule, I have lost much of my interest in it. 
If you wanna continue exploring it, you may ask me for further details.

**Comment by HinTak** [comment]
Hmm, you don't know what's in my private repo, so that's an interesting claim... In general, I don't post information or knowledge gained from decompiling / disassembling in public, to avoid possible legal problems in the future. That's why I ask about public-domain documentation on BDPDL

**Comment by lelandyang** [comment]
> 

That's interesting~
But who can say the project CAJ2PDF is not one from reverse-engineering? if one ever claims, it's merely hypocrisy.

**Comment by HinTak** [comment]
There is a difference from the legal perspective, between only analyzing and examining the CAJ files, and comparing with converted pdf outcomes, using the official software entirely as a normal user would, versus taking the official software apart / decompiling/ disassemble to study its logic. The former is okay - you are just using the software as it is normally used. The latter is questionable from a copyright stand point.

**Comment by lelandyang** [comment]
> There is a difference from the legal perspective, between only analyzing and examining the CAJ files, and comparing with converted pdf outcomes, using the official software entirely as a normal user would, versus taking the official software apart / decompiling/ disassemble to study its logic. The former is okay - you are just using the software as it is normally used. The latter is questionable from a copyright stand point.

There are laws that handles reverse engineering apart from black box testing. I don't know the case in the US, according to Computer Program Protection Act in EU, article 12-2:

>     (1) Any person who use a program according to a proper legal basis or any other person who uses the program with the former's consent may, if he is unable to easily obtain information necessary for the compatability and he needs to obtain such information, do the reverse engineering of program codes without the consent of the program copyright holder only for the part necessary for such compatibility of the relevant program.
 >   (2) Any information obtained as a result of the reverse engineering of program codes under paragraph (1) shall not be used if such information falls under the case falling under any of the following subparagraphs:
        Where it is used for other purpose than the purpose of compatibility or provided to any third person; and
        Where it is utilized for performing the act of developing, producing and selling a program that is practically similar in expression to a program subject to the reverse engineering of program codes or infringing on other program copyrights.

CAJ2PDF is **NOT** practically similar, and BDPDL is only available by reversing.

**Comment by HinTak** [comment]
Arguing about legal clauses is meaningless - you don't have the money to pay legal fees against lawyers from big companies. So just try not to do anything that would result in big companies sending their lawyers after you (rightly or wrongly), is my answer.

You are not trying to convince me that you did nothing wrong. What you need to worry about is big companies think you may be a threat (rightly or wrongly) to their business , and want to shut you down.

**Comment by HinTak** [comment]
Consider this practicality: typically if a company pay $X to lawyers to go after you, you need to spend a similar amount to $X on your own lawyers to defend yourself, however direction the outcome is. Company can afford $X, you don't.

**Comment by lelandyang** [comment]
> Arguing about legal clauses is meaningless - you don't have the money to pay legal fees against lawyers from big companies. So just try not to do anything that would result in big companies sending their lawyers after you (rightly or wrongly), is my answer.
> 
> You are not trying to convince me that you did nothing wrong. What you need to worry about is big companies think you may be a threat (rightly or wrongly) to their business , and want to shut you down.

I trying to convince nobody. if the "big company" considers us (or at least contributors to the repo) a menace to their business, I would be pleased if they file a lawsuit against all contributors and send DCMA take down requests to GitHub authority. This is what those big companies typically do when they found their source code leaked and appears on GitHub.

Please be aware, laws differs from country to country.

**Comment by HinTak** [comment]
I do not, so please do not assume your own desire is shared by others. If big companies go after you as an individual, they go after you as an individual. You do not represent other people contributing to this project.

**Comment by HinTak** [comment]
You are your own legal entity. If you get approached by company lawyers, you get your own lawyers. As you said, circumstances are different for each individual. You get lawsuit filed for yourself.

**Comment by lelandyang** [comment]
> I do not, so please do not assume your own desire is shared by others. If big companies go after you as an individual, they go after you as an individual. You do not represent other people contributing to this project.

It's naïve to say "I do not". Don't you forget you **have contributed** "information or knowledge gained from de-compiling / disassembling" as you declared (ex. project Wiki), while I didn't. 

Whereas everybody is an independent legal entity, you yourself has "infringed copyright law". Hire your own attorney now if you believe you will get lawsuit filed for yourself.

**Comment by snap950** [comment]
你好，我们有国家标准GB/T 33190-2016《电子文件存储与交换格式 版式文档》。在这里可以查到：http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=3AF6682D939116B6F5EED53D01A9DB5D。希望能给这个项目带来帮助。

Hello, we have the national standard GB/T 33190-2016 "Electronic File Storage and Exchange Format Layout Document". Here you can find: http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=3AF6682D939116B6F5EED53D01A9DB5D. Hope to help this project.

**Comment by HinTak** [comment]
I don't think the 国家标准GB/T 33190-2016《电子文件存储与交换格式 版式文档》document is relevant. But you are free to try to point out relevant sections.

If you have a caj file which does not work, please attach here.

**Comment by lelandyang** [comment]
Download a copy of 方正书版 and try to generate BDPDL files, you will find the relationship between BDPDL and the source code from which it is compiled. There is an open source parser for 方正书版 source code : https://github.com/jonix6/FBDParser
